services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: gunicorn --bind 0.0.0.0:8000 helloWorld.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
